### ISSUE TITLE
Examples and tutorials should be Jupyter Notebooks and transferred to external repository

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-PSt1/PyDynamic#140]
We discussed this already in 2018 and agreed on externalising the provided examples. These are spread over the subfolder [examples](https://github.com/PTB-PSt1/PyDynamic/tree/master/examples) and [tutorials](https://github.com/PTB-PSt1/PyDynamic/tree/master/tutorials) at the moment and should be collected in a separate repository which then will be referenced in the [docs](https://pydynamic.readthedocs.io/), the [README](https://github.com/PTB-PSt1/PyDynamic/blob/master/README.md) and everywhere applicable (e.g. inline comments).

We have now began to implement this and have already created [the repository](https://github.com/PTB-PSt1/PyDynamic_tutorials).

Future example implementations should already be created there and we need to mention and link this repository as mentioned above as the very next step.

# TODOs

- [x] create repository
- [ ] link repo in docs
- [ ] link repo in README
- [ ] start to transfer examples
